name: Deploy to AWS Lambda

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Choose deployment environment"
        options:
          - dev
          - qa
      reason:
        type: string
        description: "Reason for deployment"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Environment Variables
        run: |
          echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "REASON=${{ github.event.inputs.reason }}" >> $GITHUB_ENV

      - name: Zip Lambda Function
        run: zip function.zip index.js

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name HelloWorldLambda --zip-file fileb://function.zip
          aws lambda update-function-configuration --function-name HelloWorldLambda --environment "Variables={ENV=${{ github.event.inputs.environment }},REASON=${{ github.event.inputs.reason }}}"
